apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: trading-api-pvc
  namespace: trading-api  
  labels:
    app: trading-api
    tier: backend
spec:
  storageClassName: standard
  selector:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi