apiVersion: v1
kind: Service
metadata:
  name: trading-api
  namespace: trading-api
spec:
  selector:
    app: trading-api
    tier: backend
  ports:
    - protocol: TCP
      port: 80
  type: LoadBalancer