apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingcrm
spec:
  replicas: 3
  # strategy:
  #   rollingUpdate:
  #     maxSurge: 10%
  #     maxUnavailable: 10%
  selector:
    matchLabels:
      app: pingcrm
  template:
    metadata:
      labels:
        app: pingcrm
    spec:
      # initContainers:
      #   - name: db-migrations
      #     image: pingcrm-fpm:latest
      #     command:
      #       - "echo"
      #       # - php
      #     args:
      #       - "123"
      #       # - artisan
      #       # - db:migrate
      containers:
        - name: pingcrm-nginx
          image: danielkmariam/space-nginx:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
        - name: pingcrm-fpm
          image: danielkmariam/space-fpm:1.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9000