name: CI

on:
  push:
    branches: [ main, develop]
  pull_request:
    branches: [ develop ]
jobs:
  compose:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress
    - name: PHPUnit tests
      uses: php-actions/phpunit@v3
      with:
        configuration: phpunit.xml.dist
        memory_limit: 256M

  analyse:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress
    
    - name: Static analysis
      uses: php-actions/phpstan@v2
      with:
        command: analyse
        path: src/
        configuration: phpstan.neon
        memory_limit: 256M

  build:
    runs-on: ubuntu-latest
    needs: [compose, test, analyse]
    steps:
    - uses: actions/checkout@v2
    
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress
    
    - name: Docker login
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build
      run: docker build -t space .
    
    - name: Tags
      run: |
        docker tag space ${{ secrets.DOCKER_USERNAME }}/space:${GITHUB_SHA::12}
        docker tag space ${{ secrets.DOCKER_USERNAME }}/space:latest
    
    - name: Push
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/space:${GITHUB_SHA::12}
        docker push ${{ secrets.DOCKER_USERNAME }}/space:latest
